- name: Copy kubernetes.repo file
  copy:
    src: kubernetes.repo
    dest: /etc/yum.repos.d/kubernetes.repo

- name: Install kubelet, kubeadm, and kubectl
  dnf:
    name: "{{ item }}"
    state: present
    disable_excludes: kubernetes
  with_items:
    - kubelet
    - kubeadm
    - kubectl

- name: Enable and start kubelet service
  systemd:
    name: kubelet
    enabled: yes
    state: started